# Generated by Django 6.0.4 on 2026-04-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='What argument does this thread make?')),
                ('research_question', models.TextField(blank=True, help_text='Which research question does this address?')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('project', 'Project'), ('archive', 'Archive'), ('page', 'Page')], default='article', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('research', 'Research'), ('systems', 'Systems'), ('opinion', 'Opinion'), ('notes', 'Notes')], max_length=30)),
                ('archive_section', models.CharField(blank=True, choices=[('design', 'Design'), ('code', 'Code'), ('writing', 'Writing')], max_length=20)),
                ('body_markdown', models.TextField(blank=True, help_text='Write in Markdown. Rendered to HTML on save.')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('body_raw_html', models.TextField(blank=True, help_text='Raw HTML override. If set, used instead of Markdown.')),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, help_text='For meta tags and RSS. Auto-generated from body if blank.', max_length=500)),
                ('hero_painting', models.CharField(blank=True, help_text='Filename in writing/images/paintings/, e.g. "my-article.jpg"', max_length=200)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower = higher in nav. 0 = use date.')),
                ('shelf', models.CharField(choices=[('research', 'Research'), ('systems', 'Systems'), ('creative', 'Creative Systems'), ('archive', 'Archive')], default='archive', help_text='Research program shelf', max_length=20)),
                ('is_headline', models.BooleanField(default=False, help_text='Flagship article for the research program')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
                'unique_together': {('slug', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('builds_on', 'builds on'), ('challenges', 'challenges'), ('extends', 'extends'), ('supersedes', 'supersedes'), ('applies', 'applies'), ('evidences', 'is evidence for')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional annotation on this relationship')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='blog.article')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='blog.article')),
            ],
            options={
                'unique_together': {('source', 'target', 'relationship')},
            },
        ),
        migrations.CreateModel(
            name='ThreadArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('annotation', models.TextField(blank=True, help_text='Why this article matters in this thread')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_appearances', to='blog.article')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blog.thread')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('thread', 'article'), ('thread', 'position')},
            },
        ),
    ]
